services:
  app:
    build:
      dockerfile: ./base/Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    network_mode: service:mongodb
  mongodb:
    build:
      dockerfile: ./database/Dockerfile
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: "mongo"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodb-data: